[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags =["-Car=x86_64-linux-gnu-ar"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags =["-Car=aarch64-linux-gnu-ar"]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags =["-Car=arm-linux-gnueabihf-ar"]
