name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    with:
      docker_tag: ${{ github.ref_name }}
    secrets: inherit
